[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
script = 'scripts/foundry'
test = 'test'
cache_path  = 'cache_forge'
solc_version = '0.8.26'
auto_detect_solc = false
evm_version = 'cancun'
ignored_error_codes = [2394, 5574, 3860] # Transient storage, code size

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"