[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
script = 'scripts/'
test = 'test'
cache_path  = 'cache_forge'
evm_version = 'cancun'


[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"